apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  description: Tem como objetivo prover uma solução de orientação a eventos para a Plataforma do Backstage
  labels:
    globoi.com/featured-platform: 'true'
  name: backstage-events
spec:
  domain: backstage-development-platform
  lifecycle: production
  owner: time-backstage5
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/source-location: url:https://gitlab.globoi.com/backstage/serverless/backstage-events
    gitlab.com/project-id: '6706'
  description: Tem como objetivo prover uma solução de orientação a eventos para a Plataforma do Backstage
  links:
    - title: Docs
      url: https://docs.backstage.globoi.com/events/
  name: backstage-events
  tags:
    - python
spec:
  lifecycle: production
  providesApis:
    - backstage-events-api
  owner: time-backstage5
  system: backstage-events
  type: service
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  annotations:
    backstage.io/source-location: url:https://gitlab.globoi.com/backstage/serverless/backstage-events
  description: API para disparar um novo evento
  links:
    - title: Docs
      url: https://docs.backstage.globoi.com/events/dispatch/
  name: backstage-events-api
  tags:
    - python
spec:
  definition:
    $text: './swagger/openapi.yaml'
  lifecycle: production
  owner: time-backstage5
  system: backstage-events
  type: openapi

